-- Copyright (c) 2016-present, Facebook, Inc.
-- All rights reserved.
--
-- This source code is licensed under the BSD-style license found in the
-- LICENSE file in the root directory of this source tree. An additional grant
-- of patent rights can be found in the PATENTS file in the same directory.

-----------------------------------------------------------------
-- Auto-generated by regenClassifiers
--
-- DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
--  @generated
-----------------------------------------------------------------
{-# LANGUAGE OverloadedStrings #-}
module Duckling.Ranking.Classifiers.RU_XX (classifiers) where
import Data.String
import Prelude
import qualified Data.HashMap.Strict as HashMap
import Duckling.Ranking.Types

classifiers :: Classifiers
classifiers
  = HashMap.fromList
      [("\1073\1077\1079 <integer> <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.833213344056216,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour", -0.8266785731844679),
                                    ("integer (numeric)time-of-day (latent)", -1.6739764335716716),
                                    ("integer (3..19)time-of-day (latent)", -1.3862943611198906),
                                    ("integer (20..90)time-of-day (latent)", -2.0794415416798357)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hour diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer (numeric)",
        Classifier{okData =
                     ClassData{prior = -0.45391749149411126,
                               unseen = -4.564348191467836,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 94},
                   koData =
                     ClassData{prior = -1.0082282271998406, unseen = -4.02535169073515,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 54}}),
       ("integer (3..19)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.295836866004329,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 25},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 \1095\1072\1089",
        Classifier{okData =
                     ClassData{prior = -0.1823215567939546,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -1.791759469228055, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("integer (20..90)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 7},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal or number) <named-month>",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -1.0116009116784799),
                                    ("integer (numeric)October", -1.7047480922384253),
                                    ("integer (numeric)January", -1.2992829841302609)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -0.8873031950009028),
                                    ("integer (numeric)June", -2.1400661634962708),
                                    ("integer (numeric)October", -1.7346010553881064),
                                    ("integer (numeric)January", -2.1400661634962708),
                                    ("integer (numeric)March", -1.7346010553881064)],
                               n = 6}}),
       ("<time> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -0.8754687373538999),
                                    ("\1074 <named-day>part of days", -1.791759469228055),
                                    ("tomorrowpart of days", -1.3862943611198906),
                                    ("Mondaypart of days", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("today",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("at <time-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.21392689620928568,
                               unseen = -5.442417710521793,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> <part-of-day>", -2.665490586683414),
                                    ("half-short <hour-of-day-ordinal>", -4.339467020255086),
                                    ("<hour-of-day> <integer>", -2.493640329756755),
                                    ("<time-of-day> \1095\1072\1089\1086\1074", -3.828641396489095),
                                    ("time-of-day (latent)", -1.6094379124341003),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
                                     -3.828641396489095),
                                    ("hh:mm", -2.4423470353692043),
                                    ("half-long <hour-of-day-ordinal>", -4.74493212836325),
                                    ("hour", -1.310944923878104), ("minute", -1.546259010812569),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.74493212836325)],
                               n = 109},
                   koData =
                     ClassData{prior = -1.6471782404169475, unseen = -4.174387269895637,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.5494451709255714),
                                    ("time-of-day (latent)", -1.067840630001356),
                                    ("hhmm (latent)", -3.4657359027997265),
                                    ("hour", -1.067840630001356), ("minute", -2.367123614131617)],
                               n = 26}}),
       ("integer 1",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> \1087\1086\1087\1086\1083\1091\1076\1085\1080",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("<time-of-day> \1095\1072\1089\1086\1074",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("October",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("month (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("January",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> <part-of-day>",
        Classifier{okData =
                     ClassData{prior = -0.1686227124357927, unseen = -4.709530201312334,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1073\1077\1079 <integer> <hour-of-day>",
                                     -3.3141860046725258),
                                    ("\1074 \1095\1072\1089", -3.6018680771243066),
                                    ("at <time-of-day>", -1.927891643552635),
                                    ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
                                     -3.6018680771243066),
                                    ("half-short <hour-of-day-ordinal>", -3.0910424533583156),
                                    ("<hour-of-day> <integer>", -2.754570216737103),
                                    ("time-of-day (latent)", -1.9924301646902063),
                                    ("hh:mm", -4.007333185232471), ("hour", -1.2992829841302609),
                                    ("minute", -1.6559579280689931),
                                    ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
                                     -4.007333185232471),
                                    ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
                                     -4.007333185232471)],
                               n = 49},
                   koData =
                     ClassData{prior = -1.8632184332102, unseen = -3.4339872044851463,
                               likelihoods =
                                 HashMap.fromList
                                   [("<hour-of-day> <integer>", -2.3025850929940455),
                                    ("time-of-day (latent)", -1.3217558399823195),
                                    ("hour", -1.3217558399823195), ("minute", -2.3025850929940455)],
                               n = 9}}),
       ("hour (grain)",
        Classifier{okData =
                     ClassData{prior = -1.55814461804655, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -0.2363887780642304, unseen = -2.833213344056216,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 15}}),
       ("\1074\1099\1093\1086\1076\1085\1099\1077",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1073\1077\1079 \1095\1077\1090\1074\1077\1088\1090\1080 <hour-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3978952727983707,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half-short <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods =
                                 HashMap.fromList
                                   [("", -0.8472978603872037),
                                    ("ordinals (first..19th)", -0.5596157879354228)],
                               n = 12},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("intersect",
        Classifier{okData =
                     ClassData{prior = -0.29783444391579894,
                               unseen = -4.9344739331306915,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle><time-of-day> <part-of-day>",
                                     -4.23410650459726),
                                    ("hourday", -2.624668592163159),
                                    ("dayhour", -1.791759469228055),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month>(ordinal or number)/<named-month>/year",
                                     -4.23410650459726),
                                    ("part of days<hour-of-day> <integer>", -4.23410650459726),
                                    ("intersectat <time-of-day>", -3.828641396489095),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -3.828641396489095),
                                    ("todayat <time-of-day>", -3.828641396489095),
                                    ("at <time-of-day><day-of-month> (ordinal or number) <named-month>",
                                     -3.828641396489095),
                                    ("<time> <part-of-day>at <time-of-day>", -3.828641396489095),
                                    ("hourhour", -3.1354942159291497),
                                    ("at <time-of-day>\1074 \1095\1072\1089", -4.23410650459726),
                                    ("hourminute", -2.981343536101891),
                                    ("intersect<hour-of-day> <integer>", -4.23410650459726),
                                    ("part of daysat <time-of-day>", -3.828641396489095),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -4.23410650459726),
                                    ("at <time-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -3.828641396489095),
                                    ("<time-of-day> <part-of-day><day-of-month> (ordinal or number) of <named-month>",
                                     -3.828641396489095),
                                    ("tomorrowintersect", -3.5409593240373143),
                                    ("<time> <part-of-day><hour-of-day> <integer>",
                                     -4.23410650459726),
                                    ("part of days\1074 <named-day>", -4.23410650459726),
                                    ("\1074 <named-day>part of days", -4.23410650459726),
                                    ("<day-of-month>(ordinal or number)/<named-month>/yearat <time-of-day>",
                                     -3.5409593240373143),
                                    ("dayminute", -2.981343536101891),
                                    ("dd.mm.yyhh:mm", -4.23410650459726),
                                    ("minuteday", -4.23410650459726),
                                    ("<day-of-month>(ordinal or number)/<named-month>/year<time-of-day> <part-of-day>",
                                     -4.23410650459726),
                                    ("at <time-of-day><time-of-day> <part-of-day>",
                                     -4.23410650459726),
                                    ("today<time-of-day> <part-of-day>", -4.23410650459726),
                                    ("tomorrow<time-of-day> \1095\1072\1089\1086\1074",
                                     -4.23410650459726),
                                    ("tomorrowpart of days", -3.828641396489095),
                                    ("tomorrow<time-of-day> <part-of-day>", -4.23410650459726),
                                    ("tomorrowat <time-of-day>", -2.624668592163159),
                                    ("Mondaypart of days", -4.23410650459726)],
                               n = 49},
                   koData =
                     ClassData{prior = -1.3564413979702095, unseen = -4.31748811353631,
                               likelihoods =
                                 HashMap.fromList
                                   [("dayhour", -1.906169820405799),
                                    ("intersectat <time-of-day>", -3.6109179126442243),
                                    ("todayat <time-of-day>", -3.6109179126442243),
                                    ("<time> <part-of-day>at <time-of-day>", -3.6109179126442243),
                                    ("hourhour", -2.917770732084279),
                                    ("minutemonth", -3.20545280453606),
                                    ("part of daysat <time-of-day>", -3.6109179126442243),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>at <time-of-day>",
                                     -3.6109179126442243),
                                    ("tomorrowintersect", -3.6109179126442243),
                                    ("tomorrow<time-of-day> - <time-of-day> (interval)",
                                     -2.917770732084279),
                                    ("minuteday", -3.20545280453606),
                                    ("at <time-of-day>January", -3.6109179126442243),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) <named-month>",
                                     -3.6109179126442243),
                                    ("tomorrowat <time-of-day>", -2.6946271807700692),
                                    ("<hour-of-day> <integer> \1084\1080\1085\1091\1090<day-of-month> (ordinal or number) of <named-month>",
                                     -3.6109179126442243),
                                    ("<hour-of-day> <integer>January", -3.6109179126442243)],
                               n = 17}}),
       ("year (grain)",
        Classifier{okData =
                     ClassData{prior = -0.262364264467491, unseen = -2.4849066497880004,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 10},
                   koData =
                     ClassData{prior = -1.466337068793427, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3}}),
       ("integer 21..99",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.5108256237659907),
                                    ("integer (20..90)integer 2", -0.916290731874155)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -1.3862943611198906,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (20..90)integer (3..19)", -0.40546510810816444)],
                               n = 1}}),
       ("\1089\1087\1091\1089\1090\1103 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("year (latent)",
        Classifier{okData =
                     ClassData{prior = -0.5596157879354228,
                               unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList [("integer (numeric)", -0.1823215567939546)],
                               n = 4},
                   koData =
                     ClassData{prior = -0.8472978603872037, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.5108256237659907),
                                    ("integer 0", -0.916290731874155)],
                               n = 3}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077) <named-month>|year \1075\1086\1076\1072",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (latent)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("Monday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1095\1077\1090\1074\1077\1088\1090\1100 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hh:mm:ss",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("dd.mm.yy",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<hour-of-day> <integer>",
        Classifier{okData =
                     ClassData{prior = -0.22778393087071197,
                               unseen = -4.605170185988091,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 21..99", -3.4965075614664802),
                                    ("\1074 \1095\1072\1089integer (numeric)", -3.4965075614664802),
                                    ("at <time-of-day>integer (20..90)", -3.4965075614664802),
                                    ("time-of-day (latent)integer (numeric)", -1.9560625205193314),
                                    ("time-of-day (latent)integer (3..19)", -3.4965075614664802),
                                    ("time-of-day (latent)integer 21..99", -3.4965075614664802),
                                    ("hour", -0.8109302162163288),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer (numeric)",
                                     -3.2088254890146994),
                                    ("at <time-of-day>integer (numeric)", -2.030170492673053),
                                    ("at <time-of-day>integer (3..19)", -3.4965075614664802),
                                    ("time-of-day (latent)integer (20..90)", -3.2088254890146994)],
                               n = 43},
                   koData =
                     ClassData{prior = -1.5910887737659039, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (20..90)", -2.456735772821304),
                                    ("time-of-day (latent)integer (numeric)", -2.169053700369523),
                                    ("hour", -1.0704414117014134),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer (numeric)",
                                     -2.8622008809294686),
                                    ("time-of-day (latent)integer 2", -2.8622008809294686),
                                    ("at <time-of-day>integer (numeric)", -2.8622008809294686),
                                    ("time-of-day (latent)integer (20..90)", -2.456735772821304)],
                               n = 11}}),
       ("<duration> \1089\1087\1091\1089\1090\1103|\1085\1072\1079\1072\1076",
        Classifier{okData =
                     ClassData{prior = -0.2876820724517809,
                               unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("second", -1.791759469228055),
                                    ("<integer> \1089\1091\1090\1086\1082", -1.791759469228055),
                                    ("a <unit-of-duration>", -1.791759469228055),
                                    ("hour", -1.791759469228055), ("month", -1.791759469228055),
                                    ("<positive-numeral> <time-grain>", -1.791759469228055)],
                               n = 3},
                   koData =
                     ClassData{prior = -1.3862943611198906,
                               unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("a <unit-of-duration>", -1.3862943611198906),
                                    ("hour", -1.3862943611198906)],
                               n = 1}}),
       ("week (grain)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.3025850929940455,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 8},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1076\1077\1085\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<day-of-month> (ordinal or number) of <named-month>",
        Classifier{okData =
                     ClassData{prior = -1.0986122886681098,
                               unseen = -2.4849066497880004,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -1.0116009116784799),
                                    ("integer (numeric)October", -1.7047480922384253),
                                    ("integer (numeric)January", -1.2992829841302609)],
                               n = 3},
                   koData =
                     ClassData{prior = -0.40546510810816444,
                               unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -0.8873031950009028),
                                    ("integer (numeric)June", -2.1400661634962708),
                                    ("integer (numeric)October", -1.7346010553881064),
                                    ("integer (numeric)January", -2.1400661634962708),
                                    ("integer (numeric)March", -1.7346010553881064)],
                               n = 6}}),
       ("\1101\1090\1086\1090 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.6931471805599453),
                                    ("year", -0.6931471805599453)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074(\1090\1077\1095\1077\1085\1080\1077) <named-month>|year",
        Classifier{okData =
                     ClassData{prior = -0.3184537311185346, unseen = -2.995732273553991,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (latent)", -1.3350010667323402),
                                    ("year", -0.7472144018302211),
                                    ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
                                     -1.3350010667323402)],
                               n = 8},
                   koData =
                     ClassData{prior = -1.2992829841302609,
                               unseen = -2.3025850929940455,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (latent)", -0.8109302162163288),
                                    ("year", -0.8109302162163288)],
                               n = 3}}),
       ("tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 11},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 2",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> \1095\1072\1089\1086\1074",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.4011973816621555,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.7578579175523736),
                                    ("time-of-day (latent)", -1.0647107369924282),
                                    ("hour", -0.7282385003712154)],
                               n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("June",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1089\1091\1090\1086\1082",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("integer (numeric)", 0.0)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute (grain)",
        Classifier{okData =
                     ClassData{prior = -1.2237754316221157,
                               unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 5},
                   koData =
                     ClassData{prior = -0.3483066942682157, unseen = -2.639057329615259,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 12}}),
       ("time-of-day (latent)",
        Classifier{okData =
                     ClassData{prior = -0.4207325802389528, unseen = -4.276666119016055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.4340384805522204),
                                    ("integer (3..19)", -1.3723081191451507),
                                    ("integer 1", -3.56953269648137),
                                    ("integer 21..99", -3.56953269648137),
                                    ("integer 0", -3.56953269648137)],
                               n = 65},
                   koData =
                     ClassData{prior = -1.0687593255184287, unseen = -3.713572066704308,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)", -0.19237189264745613),
                                    ("integer (3..19)", -2.995732273553991),
                                    ("integer (20..90)", -2.995732273553991)],
                               n = 34}}),
       ("<integer> <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -1.3609765531356008, unseen = -3.58351893845611,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -1.6094379124341003),
                                    ("integer 2week (grain)", -2.456735772821304),
                                    ("integer (numeric)week (grain)", -1.9459101490553135),
                                    ("integer (3..19)minute (grain)", -2.8622008809294686),
                                    ("integer (numeric)minute (grain)", -2.169053700369523),
                                    ("minute", -1.9459101490553135)],
                               n = 10},
                   koData =
                     ClassData{prior = -0.2962658161431724, unseen = -4.304065093204169,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)day (grain)", -2.498699971920336),
                                    ("integer (3..19)day (grain)", -3.597312260588446),
                                    ("integer (numeric)year (grain)", -2.9041650800285006),
                                    ("day", -2.211017899468555), ("year", -2.9041650800285006),
                                    ("hour", -1.9878743481543455),
                                    ("integer (numeric)minute (grain)", -1.8925641683500207),
                                    ("integer (3..19)hour (grain)", -3.597312260588446),
                                    ("minute", -1.8925641683500207),
                                    ("integer (numeric)hour (grain)", -2.093234863812172),
                                    ("integer 1day (grain)", -3.597312260588446)],
                               n = 29}}),
       ("ordinals (first..19th)",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.70805020110221,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 13},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("hhmm (latent)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1}}),
       ("<hour-of-day> <integer> \1084\1080\1085\1091\1090",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.5553480614894135,
                               likelihoods =
                                 HashMap.fromList
                                   [("time-of-day (latent)integer (numeric)", -2.4277482359480516),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer 0",
                                     -2.4277482359480516),
                                    ("hour", -0.8183103235139514),
                                    ("<time-of-day> \1095\1072\1089\1086\1074integer (numeric)",
                                     -1.580450375560848),
                                    ("at <time-of-day>integer (numeric)", -2.1400661634962708),
                                    ("at <time-of-day>integer 0", -2.833213344056216)],
                               n = 14},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.9459101490553135,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("a <unit-of-duration>",
        Classifier{okData =
                     ClassData{prior = -2.3025850929940455, unseen = -3.295836866004329,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.159484249353372),
                                    ("month (grain)", -1.8718021769015913),
                                    ("hour (grain)", -2.5649493574615367),
                                    ("week (grain)", -2.159484249353372),
                                    ("minute (grain)", -2.5649493574615367),
                                    ("hour", -2.5649493574615367), ("month", -1.8718021769015913),
                                    ("minute", -2.5649493574615367)],
                               n = 7},
                   koData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -4.9344739331306915,
                               likelihoods =
                                 HashMap.fromList
                                   [("week", -2.981343536101891),
                                    ("hour (grain)", -1.9828147059907641),
                                    ("year (grain)", -2.2881963555419462),
                                    ("week (grain)", -2.981343536101891),
                                    ("day", -2.5293584123588344),
                                    ("minute (grain)", -2.0940403411009885),
                                    ("year", -2.2881963555419462), ("hour", -1.9828147059907641),
                                    ("minute", -2.0940403411009885),
                                    ("day (grain)", -2.5293584123588344)],
                               n = 63}}),
       ("hh:mm",
        Classifier{okData =
                     ClassData{prior = -9.097177820572676e-2,
                               unseen = -3.1354942159291497,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 21},
                   koData =
                     ClassData{prior = -2.4423470353692043,
                               unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("\1085\1072 \1087\1088\1086\1096\1077\1076\1096\1077\1081 <time>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("\1074\1099\1093\1086\1076\1085\1099\1077",
                                     -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("minute diminutive",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("quarter of an hour",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("half-long <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("ordinals (first..19th)", 0.0)],
                               n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("March",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1095\1077\1088\1077\1079|\1074 \1090\1077\1095\1077\1085\1080\1077|\1087\1086\1089\1083\1077 <duration>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -4.07753744390572,
                               likelihoods =
                                 HashMap.fromList
                                   [("hour diminutive", -2.6741486494265287),
                                    ("week", -1.8632184332102), ("second", -3.367295829986474),
                                    ("<integer> \1089\1091\1090\1086\1082", -3.367295829986474),
                                    ("<integer> <unit-of-duration>", -1.6625477377480489),
                                    ("a <unit-of-duration>", -2.268683541318364),
                                    ("minute diminutive", -2.9618307218783095),
                                    ("quarter of an hour", -3.367295829986474),
                                    ("hour", -2.268683541318364), ("month", -3.367295829986474),
                                    ("minute", -1.8632184332102),
                                    ("<positive-numeral> <time-grain>", -3.367295829986474)],
                               n = 23},
                   koData =
                     ClassData{prior = -infinity, unseen = -2.5649493574615367,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day-before-yesterday",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("decimal number",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2}}),
       ("<day-of-month>(ordinal or number)/<named-month>/year",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.890371757896165,
                               likelihoods =
                                 HashMap.fromList
                                   [("month", -0.8873031950009028),
                                    ("integer (numeric)June", -2.1400661634962708),
                                    ("integer (numeric)October", -1.7346010553881064),
                                    ("integer (numeric)January", -2.1400661634962708),
                                    ("integer (numeric)March", -1.7346010553881064)],
                               n = 6},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<time-of-day> - <time-of-day> (interval)",
        Classifier{okData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0},
                   koData =
                     ClassData{prior = 0.0, unseen = -3.1354942159291497,
                               likelihoods =
                                 HashMap.fromList
                                   [("hh:mmtime-of-day (latent)", -2.3978952727983707),
                                    ("hourhour", -0.8938178760220964),
                                    ("minutehour", -2.3978952727983707),
                                    ("at <time-of-day>time-of-day (latent)", -0.8938178760220964)],
                               n = 9}}),
       ("decimal one and a half",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1087\1086\1083\1085\1086\1095\1100",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("integer 0",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.3862943611198906,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1090\1077\1082\1091\1097\1080\1081|\1089\1083\1077\1076\1091\1102\1097\1080\1081|\1087\1088\1086\1096\1083\1099\1081 <cycle>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -3.2188758248682006,
                               likelihoods =
                                 HashMap.fromList
                                   [("year (grain)", -0.8754687373538999),
                                    ("day", -2.4849066497880004), ("year", -0.8754687373538999),
                                    ("day (grain)", -2.4849066497880004)],
                               n = 10},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1074 <named-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.9459101490553135,
                               likelihoods =
                                 HashMap.fromList
                                   [("Monday", -0.6931471805599453), ("day", -0.6931471805599453)],
                               n = 2},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day (grain)",
        Classifier{okData =
                     ClassData{prior = -2.3025850929940455,
                               unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -0.10536051565782628,
                               unseen = -2.3978952727983707,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 9}}),
       ("right now",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("\1088\1086\1074\1085\1086|\1090\1086\1095\1085\1086 <time-of-day>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.5649493574615367,
                               likelihoods =
                                 HashMap.fromList
                                   [("at <time-of-day>", -1.3862943611198906),
                                    ("<time-of-day> <part-of-day>", -1.791759469228055),
                                    ("hour", -0.8754687373538999),
                                    ("\1087\1086\1083\1085\1086\1095\1100", -1.791759469228055)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.6094379124341003,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("day-after-tomorrow",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 1},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("part of days",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods = HashMap.fromList [("", 0.0)], n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<integer> \1084\1080\1085\1091\1090 <hour-of-day-ordinal>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -1.791759469228055,
                               likelihoods =
                                 HashMap.fromList
                                   [("integer (numeric)ordinals (first..19th)", 0.0)],
                               n = 4},
                   koData =
                     ClassData{prior = -infinity, unseen = -0.6931471805599453,
                               likelihoods = HashMap.fromList [], n = 0}}),
       ("<positive-numeral> <time-grain>",
        Classifier{okData =
                     ClassData{prior = 0.0, unseen = -2.1972245773362196,
                               likelihoods =
                                 HashMap.fromList
                                   [("decimal one and a halfhour (grain)", -0.6931471805599453),
                                    ("hour", -0.6931471805599453)],
                               n = 3},
                   koData =
                     ClassData{prior = -infinity, unseen = -1.0986122886681098,
                               likelihoods = HashMap.fromList [], n = 0}})]